#FROM golang:alpine as build
FROM ubi8/go-toolset as build

WORKDIR /opt/app-root
ENV GOPATH=/opt/app-root/
COPY src src
WORKDIR /opt/app-root/src/spearedge/
      
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /tmp/spearedge

FROM ubi8/ubi-minimal

WORKDIR /opt/app-root
COPY --from=build /tmp/spearedge /opt/app-root/spearedge


EXPOSE 8080
CMD ["/opt/app-root/spearedge"]
ENTRYPOINT ["/opt/app-root/spearedge"]