apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spearedge
spec:
  rules:
  - host: '<change me>'
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spearedge
            port:
              number: 8080
