apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portcheck
spec:
  rules:
  - host: "{{ portcheck_hostname }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portcheck
            port:
              number: 8080
